#if !Py_TAIL_CALL_INTERP
static void *opcode_targets[256] = {
    &&TARGET_CACHE,
    &&TARGET_POP_TOP,
    &&TARGET_PUSH_NULL,
    &&TARGET_INTERPRETER_EXIT,
    &&TARGET_END_FOR,
    &&TARGET_END_SEND,
    &&TARGET_BINARY_OP_ADD_FLOAT,
    &&TARGET_BINARY_OP_ADD_INT,
    &&TARGET_BINARY_OP_ADD_UNICODE,
    &&TARGET_NOP,
    &&TARGET_BINARY_OP_INPLACE_ADD_UNICODE,
    &&TARGET_UNARY_NEGATIVE,
    &&TARGET_UNARY_NOT,
    &&TARGET_BINARY_OP_MULTIPLY_FLOAT,
    &&TARGET_BINARY_OP_MULTIPLY_INT,
    &&TARGET_UNARY_INVERT,
    &&TARGET_BINARY_OP_SUBTRACT_FLOAT,
    &&TARGET_RESERVED,
    &&TARGET_BINARY_OP_SUBTRACT_INT,
    &&TARGET_BINARY_SUBSCR_DICT,
    &&TARGET_BINARY_SUBSCR_GETITEM,
    &&TARGET_BINARY_SUBSCR_LIST_INT,
    &&TARGET_BINARY_SUBSCR_TUPLE_INT,
    &&TARGET_CALL_PY_EXACT_ARGS,
    &&TARGET_CALL_PY_WITH_DEFAULTS,
    &&TARGET_BINARY_SUBSCR,
    &&TARGET_BINARY_SLICE,
    &&TARGET_STORE_SLICE,
    &&TARGET_CALL_BOUND_METHOD_EXACT_ARGS,
    &&TARGET_CALL_BUILTIN_CLASS,
    &&TARGET_GET_LEN,
    &&TARGET_MATCH_MAPPING,
    &&TARGET_MATCH_SEQUENCE,
    &&TARGET_MATCH_KEYS,
    &&TARGET_CALL_BUILTIN_FAST_WITH_KEYWORDS,
    &&TARGET_PUSH_EXC_INFO,
    &&TARGET_CHECK_EXC_MATCH,
    &&TARGET_CHECK_EG_MATCH,
    &&TARGET_CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS,
    &&TARGET_CALL_NO_KW_BUILTIN_FAST,
    &&TARGET_CALL_NO_KW_BUILTIN_O,
    &&TARGET_CALL_NO_KW_ISINSTANCE,
    &&TARGET_CALL_NO_KW_LEN,
    &&TARGET_CALL_NO_KW_LIST_APPEND,
    &&TARGET_CALL_NO_KW_METHOD_DESCRIPTOR_FAST,
    &&TARGET_CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS,
    &&TARGET_CALL_NO_KW_METHOD_DESCRIPTOR_O,
    &&TARGET_CALL_NO_KW_STR_1,
    &&TARGET_CALL_NO_KW_TUPLE_1,
    &&TARGET_WITH_EXCEPT_START,
    &&TARGET_GET_AITER,
    &&TARGET_GET_ANEXT,
    &&TARGET_BEFORE_ASYNC_WITH,
    &&TARGET_BEFORE_WITH,
    &&TARGET_END_ASYNC_FOR,
    &&TARGET_CLEANUP_THROW,
    &&TARGET_CALL_NO_KW_TYPE_1,
    &&TARGET_COMPARE_OP_FLOAT,
    &&TARGET_COMPARE_OP_INT,
    &&TARGET_COMPARE_OP_STR,
    &&TARGET_STORE_SUBSCR,
    &&TARGET_DELETE_SUBSCR,
    &&TARGET_FOR_ITER_LIST,
    &&TARGET_FOR_ITER_TUPLE,
    &&TARGET_FOR_ITER_RANGE,
    &&TARGET_FOR_ITER_GEN,
    &&TARGET_LOAD_SUPER_ATTR_ATTR,
    &&TARGET_LOAD_SUPER_ATTR_METHOD,
    &&TARGET_GET_ITER,
    &&TARGET_GET_YIELD_FROM_ITER,
    &&TARGET_LOAD_ATTR_CLASS,
    &&TARGET_LOAD_BUILD_CLASS,
    &&TARGET_LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN,
    &&TARGET_LOAD_ATTR_INSTANCE_VALUE,
    &&TARGET_LOAD_ASSERTION_ERROR,
    &&TARGET_RETURN_GENERATOR,
    &&TARGET_LOAD_ATTR_MODULE,
    &&TARGET_LOAD_ATTR_PROPERTY,
    &&TARGET_LOAD_ATTR_SLOT,
    &&TARGET_LOAD_ATTR_WITH_HINT,
    &&TARGET_LOAD_ATTR_METHOD_LAZY_DICT,
    &&TARGET_LOAD_ATTR_METHOD_NO_DICT,
    &&TARGET_LOAD_ATTR_METHOD_WITH_VALUES,
    &&TARGET_RETURN_VALUE,
    &&TARGET_LOAD_CONST__LOAD_FAST,
    &&TARGET_SETUP_ANNOTATIONS,
    &&TARGET_LOAD_FAST__LOAD_CONST,
    &&TARGET_LOAD_LOCALS,
    &&TARGET_LOAD_FAST__LOAD_FAST,
    &&TARGET_POP_EXCEPT,
    &&TARGET_STORE_NAME,
    &&TARGET_DELETE_NAME,
    &&TARGET_UNPACK_SEQUENCE,
    &&TARGET_FOR_ITER,
    &&TARGET_UNPACK_EX,
    &&TARGET_STORE_ATTR,
    &&TARGET_DELETE_ATTR,
    &&TARGET_STORE_GLOBAL,
    &&TARGET_DELETE_GLOBAL,
    &&TARGET_SWAP,
    &&TARGET_LOAD_CONST,
    &&TARGET_LOAD_NAME,
    &&TARGET_BUILD_TUPLE,
    &&TARGET_BUILD_LIST,
    &&TARGET_BUILD_SET,
    &&TARGET_BUILD_MAP,
    &&TARGET_LOAD_ATTR,
    &&TARGET_COMPARE_OP,
    &&TARGET_IMPORT_NAME,
    &&TARGET_IMPORT_FROM,
    &&TARGET_JUMP_FORWARD,
    &&TARGET_LOAD_GLOBAL_BUILTIN,
    &&TARGET_LOAD_GLOBAL_MODULE,
    &&TARGET_STORE_ATTR_INSTANCE_VALUE,
    &&TARGET_POP_JUMP_IF_FALSE,
    &&TARGET_POP_JUMP_IF_TRUE,
    &&TARGET_LOAD_GLOBAL,
    &&TARGET_IS_OP,
    &&TARGET_CONTAINS_OP,
    &&TARGET_RERAISE,
    &&TARGET_COPY,
    &&TARGET_RETURN_CONST,
    &&TARGET_BINARY_OP,
    &&TARGET_SEND,
    &&TARGET_LOAD_FAST,
    &&TARGET_STORE_FAST,
    &&TARGET_DELETE_FAST,
    &&TARGET_LOAD_FAST_CHECK,
    &&TARGET_POP_JUMP_IF_NOT_NONE,
    &&TARGET_POP_JUMP_IF_NONE,
    &&TARGET_RAISE_VARARGS,
    &&TARGET_GET_AWAITABLE,
    &&TARGET_MAKE_FUNCTION,
    &&TARGET_BUILD_SLICE,
    &&TARGET_JUMP_BACKWARD_NO_INTERRUPT,
    &&TARGET_MAKE_CELL,
    &&TARGET_LOAD_CLOSURE,
    &&TARGET_LOAD_DEREF,
    &&TARGET_STORE_DEREF,
    &&TARGET_DELETE_DEREF,
    &&TARGET_JUMP_BACKWARD,
    &&TARGET_LOAD_SUPER_ATTR,
    &&TARGET_CALL_FUNCTION_EX,
    &&TARGET_LOAD_FAST_AND_CLEAR,
    &&TARGET_EXTENDED_ARG,
    &&TARGET_LIST_APPEND,
    &&TARGET_SET_ADD,
    &&TARGET_MAP_ADD,
    &&TARGET_STORE_ATTR_SLOT,
    &&TARGET_COPY_FREE_VARS,
    &&TARGET_YIELD_VALUE,
    &&TARGET_RESUME,
    &&TARGET_MATCH_CLASS,
    &&TARGET_STORE_ATTR_WITH_HINT,
    &&TARGET_STORE_FAST__LOAD_FAST,
    &&TARGET_FORMAT_VALUE,
    &&TARGET_BUILD_CONST_KEY_MAP,
    &&TARGET_BUILD_STRING,
    &&TARGET_STORE_FAST__STORE_FAST,
    &&TARGET_STORE_SUBSCR_DICT,
    &&TARGET_STORE_SUBSCR_LIST_INT,
    &&TARGET_UNPACK_SEQUENCE_LIST,
    &&TARGET_LIST_EXTEND,
    &&TARGET_SET_UPDATE,
    &&TARGET_DICT_MERGE,
    &&TARGET_DICT_UPDATE,
    &&TARGET_UNPACK_SEQUENCE_TUPLE,
    &&TARGET_UNPACK_SEQUENCE_TWO_TUPLE,
    &&TARGET_SEND_GEN,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&TARGET_CALL,
    &&TARGET_KW_NAMES,
    &&TARGET_CALL_INTRINSIC_1,
    &&TARGET_CALL_INTRINSIC_2,
    &&TARGET_LOAD_FROM_DICT_OR_GLOBALS,
    &&TARGET_LOAD_FROM_DICT_OR_DEREF,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&_unknown_opcode,
    &&TARGET_INSTRUMENTED_LOAD_SUPER_ATTR,
    &&TARGET_INSTRUMENTED_POP_JUMP_IF_NONE,
    &&TARGET_INSTRUMENTED_POP_JUMP_IF_NOT_NONE,
    &&TARGET_INSTRUMENTED_RESUME,
    &&TARGET_INSTRUMENTED_CALL,
    &&TARGET_INSTRUMENTED_RETURN_VALUE,
    &&TARGET_INSTRUMENTED_YIELD_VALUE,
    &&TARGET_INSTRUMENTED_CALL_FUNCTION_EX,
    &&TARGET_INSTRUMENTED_JUMP_FORWARD,
    &&TARGET_INSTRUMENTED_JUMP_BACKWARD,
    &&TARGET_INSTRUMENTED_RETURN_CONST,
    &&TARGET_INSTRUMENTED_FOR_ITER,
    &&TARGET_INSTRUMENTED_POP_JUMP_IF_FALSE,
    &&TARGET_INSTRUMENTED_POP_JUMP_IF_TRUE,
    &&TARGET_INSTRUMENTED_END_FOR,
    &&TARGET_INSTRUMENTED_END_SEND,
    &&TARGET_INSTRUMENTED_INSTRUCTION,
    &&TARGET_INSTRUMENTED_LINE,
    &&_unknown_opcode
};
#else /* Py_TAIL_CALL_INTERP */

static py_tail_call_funcptr INSTRUCTION_TABLE[256];

Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_handle_eval_breaker(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_unbound_local_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_pop_4_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_pop_3_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_pop_2_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_pop_1_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_exception_unwind(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_exit_unwind(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_resume_with_error(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_start_frame(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_resume_frame(TAIL_CALL_PARAMS);

Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CACHE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_POP_TOP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_PUSH_NULL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INTERPRETER_EXIT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_END_FOR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_END_SEND(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_ADD_FLOAT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_ADD_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_ADD_UNICODE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_NOP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_INPLACE_ADD_UNICODE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNARY_NEGATIVE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNARY_NOT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_MULTIPLY_FLOAT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_MULTIPLY_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNARY_INVERT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_SUBTRACT_FLOAT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RESERVED(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP_SUBTRACT_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_SUBSCR_DICT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_SUBSCR_GETITEM(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_SUBSCR_LIST_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_SUBSCR_TUPLE_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_PY_EXACT_ARGS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_PY_WITH_DEFAULTS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_SUBSCR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_SLICE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_SLICE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_BOUND_METHOD_EXACT_ARGS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_BUILTIN_CLASS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_GET_LEN(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MATCH_MAPPING(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MATCH_SEQUENCE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MATCH_KEYS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_BUILTIN_FAST_WITH_KEYWORDS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_PUSH_EXC_INFO(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CHECK_EXC_MATCH(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CHECK_EG_MATCH(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_BUILTIN_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_BUILTIN_O(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_ISINSTANCE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_LEN(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_LIST_APPEND(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_METHOD_DESCRIPTOR_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_METHOD_DESCRIPTOR_O(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_STR_1(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_TUPLE_1(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_WITH_EXCEPT_START(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_GET_AITER(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_GET_ANEXT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BEFORE_ASYNC_WITH(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BEFORE_WITH(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_END_ASYNC_FOR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CLEANUP_THROW(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_NO_KW_TYPE_1(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_COMPARE_OP_FLOAT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_COMPARE_OP_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_COMPARE_OP_STR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_SUBSCR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DELETE_SUBSCR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_FOR_ITER_LIST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_FOR_ITER_TUPLE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_FOR_ITER_RANGE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_FOR_ITER_GEN(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_SUPER_ATTR_ATTR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_SUPER_ATTR_METHOD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_GET_ITER(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_GET_YIELD_FROM_ITER(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_CLASS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_BUILD_CLASS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_INSTANCE_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ASSERTION_ERROR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RETURN_GENERATOR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_MODULE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_PROPERTY(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_SLOT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_WITH_HINT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_METHOD_LAZY_DICT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_METHOD_NO_DICT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR_METHOD_WITH_VALUES(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RETURN_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_CONST__LOAD_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_SETUP_ANNOTATIONS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FAST__LOAD_CONST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_LOCALS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FAST__LOAD_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_POP_EXCEPT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_NAME(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DELETE_NAME(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNPACK_SEQUENCE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_FOR_ITER(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNPACK_EX(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_ATTR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DELETE_ATTR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_GLOBAL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DELETE_GLOBAL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_SWAP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_CONST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_NAME(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_TUPLE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_LIST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_SET(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_MAP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_ATTR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_COMPARE_OP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_IMPORT_NAME(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_IMPORT_FROM(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_JUMP_FORWARD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_GLOBAL_BUILTIN(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_GLOBAL_MODULE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_ATTR_INSTANCE_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_POP_JUMP_IF_FALSE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_POP_JUMP_IF_TRUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_GLOBAL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_IS_OP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CONTAINS_OP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RERAISE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_COPY(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RETURN_CONST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BINARY_OP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_SEND(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DELETE_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FAST_CHECK(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_POP_JUMP_IF_NOT_NONE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_POP_JUMP_IF_NONE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RAISE_VARARGS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_GET_AWAITABLE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MAKE_FUNCTION(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_SLICE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_JUMP_BACKWARD_NO_INTERRUPT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MAKE_CELL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_CLOSURE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_DEREF(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_DEREF(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DELETE_DEREF(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_JUMP_BACKWARD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_SUPER_ATTR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_FUNCTION_EX(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FAST_AND_CLEAR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_EXTENDED_ARG(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LIST_APPEND(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_SET_ADD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MAP_ADD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_ATTR_SLOT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_COPY_FREE_VARS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_YIELD_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_RESUME(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_MATCH_CLASS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_ATTR_WITH_HINT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_FAST__LOAD_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_FORMAT_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_CONST_KEY_MAP(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_BUILD_STRING(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_FAST__STORE_FAST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_SUBSCR_DICT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_STORE_SUBSCR_LIST_INT(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNPACK_SEQUENCE_LIST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LIST_EXTEND(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_SET_UPDATE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DICT_MERGE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_DICT_UPDATE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNPACK_SEQUENCE_TUPLE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNPACK_SEQUENCE_TWO_TUPLE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_SEND_GEN(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_KW_NAMES(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_INTRINSIC_1(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_CALL_INTRINSIC_2(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FROM_DICT_OR_GLOBALS(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_LOAD_FROM_DICT_OR_DEREF(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_LOAD_SUPER_ATTR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_NONE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_NOT_NONE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_RESUME(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_CALL(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_RETURN_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_YIELD_VALUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_CALL_FUNCTION_EX(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_JUMP_FORWARD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_JUMP_BACKWARD(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_RETURN_CONST(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_FOR_ITER(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_FALSE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_TRUE(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_END_FOR(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_END_SEND(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_INSTRUCTION(TAIL_CALL_PARAMS);
Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_INSTRUMENTED_LINE(TAIL_CALL_PARAMS);

Py_PRESERVE_NONE_CC static PyObject *_TAIL_CALL_UNKNOWN_OPCODE(TAIL_CALL_PARAMS) {
    int opcode = next_instr->op.code;
    _PyErr_Format(tstate, PyExc_SystemError,
                  "%U:%d: unknown opcode %d",
                  frame->f_code->co_filename,
                  PyUnstable_InterpreterFrame_GetLine(frame),
                  opcode);
    JUMP_TO_LABEL(error);
}

static py_tail_call_funcptr INSTRUCTION_TABLE[256] = {
    [CACHE] = _TAIL_CALL_CACHE,
    [POP_TOP] = _TAIL_CALL_POP_TOP,
    [PUSH_NULL] = _TAIL_CALL_PUSH_NULL,
    [INTERPRETER_EXIT] = _TAIL_CALL_INTERPRETER_EXIT,
    [END_FOR] = _TAIL_CALL_END_FOR,
    [END_SEND] = _TAIL_CALL_END_SEND,
    [BINARY_OP_ADD_FLOAT] = _TAIL_CALL_BINARY_OP_ADD_FLOAT,
    [BINARY_OP_ADD_INT] = _TAIL_CALL_BINARY_OP_ADD_INT,
    [BINARY_OP_ADD_UNICODE] = _TAIL_CALL_BINARY_OP_ADD_UNICODE,
    [NOP] = _TAIL_CALL_NOP,
    [BINARY_OP_INPLACE_ADD_UNICODE] = _TAIL_CALL_BINARY_OP_INPLACE_ADD_UNICODE,
    [UNARY_NEGATIVE] = _TAIL_CALL_UNARY_NEGATIVE,
    [UNARY_NOT] = _TAIL_CALL_UNARY_NOT,
    [BINARY_OP_MULTIPLY_FLOAT] = _TAIL_CALL_BINARY_OP_MULTIPLY_FLOAT,
    [BINARY_OP_MULTIPLY_INT] = _TAIL_CALL_BINARY_OP_MULTIPLY_INT,
    [UNARY_INVERT] = _TAIL_CALL_UNARY_INVERT,
    [BINARY_OP_SUBTRACT_FLOAT] = _TAIL_CALL_BINARY_OP_SUBTRACT_FLOAT,
    [RESERVED] = _TAIL_CALL_RESERVED,
    [BINARY_OP_SUBTRACT_INT] = _TAIL_CALL_BINARY_OP_SUBTRACT_INT,
    [BINARY_SUBSCR_DICT] = _TAIL_CALL_BINARY_SUBSCR_DICT,
    [BINARY_SUBSCR_GETITEM] = _TAIL_CALL_BINARY_SUBSCR_GETITEM,
    [BINARY_SUBSCR_LIST_INT] = _TAIL_CALL_BINARY_SUBSCR_LIST_INT,
    [BINARY_SUBSCR_TUPLE_INT] = _TAIL_CALL_BINARY_SUBSCR_TUPLE_INT,
    [CALL_PY_EXACT_ARGS] = _TAIL_CALL_CALL_PY_EXACT_ARGS,
    [CALL_PY_WITH_DEFAULTS] = _TAIL_CALL_CALL_PY_WITH_DEFAULTS,
    [BINARY_SUBSCR] = _TAIL_CALL_BINARY_SUBSCR,
    [BINARY_SLICE] = _TAIL_CALL_BINARY_SLICE,
    [STORE_SLICE] = _TAIL_CALL_STORE_SLICE,
    [CALL_BOUND_METHOD_EXACT_ARGS] = _TAIL_CALL_CALL_BOUND_METHOD_EXACT_ARGS,
    [CALL_BUILTIN_CLASS] = _TAIL_CALL_CALL_BUILTIN_CLASS,
    [GET_LEN] = _TAIL_CALL_GET_LEN,
    [MATCH_MAPPING] = _TAIL_CALL_MATCH_MAPPING,
    [MATCH_SEQUENCE] = _TAIL_CALL_MATCH_SEQUENCE,
    [MATCH_KEYS] = _TAIL_CALL_MATCH_KEYS,
    [CALL_BUILTIN_FAST_WITH_KEYWORDS] = _TAIL_CALL_CALL_BUILTIN_FAST_WITH_KEYWORDS,
    [PUSH_EXC_INFO] = _TAIL_CALL_PUSH_EXC_INFO,
    [CHECK_EXC_MATCH] = _TAIL_CALL_CHECK_EXC_MATCH,
    [CHECK_EG_MATCH] = _TAIL_CALL_CHECK_EG_MATCH,
    [CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS] = _TAIL_CALL_CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS,
    [CALL_NO_KW_BUILTIN_FAST] = _TAIL_CALL_CALL_NO_KW_BUILTIN_FAST,
    [CALL_NO_KW_BUILTIN_O] = _TAIL_CALL_CALL_NO_KW_BUILTIN_O,
    [CALL_NO_KW_ISINSTANCE] = _TAIL_CALL_CALL_NO_KW_ISINSTANCE,
    [CALL_NO_KW_LEN] = _TAIL_CALL_CALL_NO_KW_LEN,
    [CALL_NO_KW_LIST_APPEND] = _TAIL_CALL_CALL_NO_KW_LIST_APPEND,
    [CALL_NO_KW_METHOD_DESCRIPTOR_FAST] = _TAIL_CALL_CALL_NO_KW_METHOD_DESCRIPTOR_FAST,
    [CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS] = _TAIL_CALL_CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS,
    [CALL_NO_KW_METHOD_DESCRIPTOR_O] = _TAIL_CALL_CALL_NO_KW_METHOD_DESCRIPTOR_O,
    [CALL_NO_KW_STR_1] = _TAIL_CALL_CALL_NO_KW_STR_1,
    [CALL_NO_KW_TUPLE_1] = _TAIL_CALL_CALL_NO_KW_TUPLE_1,
    [WITH_EXCEPT_START] = _TAIL_CALL_WITH_EXCEPT_START,
    [GET_AITER] = _TAIL_CALL_GET_AITER,
    [GET_ANEXT] = _TAIL_CALL_GET_ANEXT,
    [BEFORE_ASYNC_WITH] = _TAIL_CALL_BEFORE_ASYNC_WITH,
    [BEFORE_WITH] = _TAIL_CALL_BEFORE_WITH,
    [END_ASYNC_FOR] = _TAIL_CALL_END_ASYNC_FOR,
    [CLEANUP_THROW] = _TAIL_CALL_CLEANUP_THROW,
    [CALL_NO_KW_TYPE_1] = _TAIL_CALL_CALL_NO_KW_TYPE_1,
    [COMPARE_OP_FLOAT] = _TAIL_CALL_COMPARE_OP_FLOAT,
    [COMPARE_OP_INT] = _TAIL_CALL_COMPARE_OP_INT,
    [COMPARE_OP_STR] = _TAIL_CALL_COMPARE_OP_STR,
    [STORE_SUBSCR] = _TAIL_CALL_STORE_SUBSCR,
    [DELETE_SUBSCR] = _TAIL_CALL_DELETE_SUBSCR,
    [FOR_ITER_LIST] = _TAIL_CALL_FOR_ITER_LIST,
    [FOR_ITER_TUPLE] = _TAIL_CALL_FOR_ITER_TUPLE,
    [FOR_ITER_RANGE] = _TAIL_CALL_FOR_ITER_RANGE,
    [FOR_ITER_GEN] = _TAIL_CALL_FOR_ITER_GEN,
    [LOAD_SUPER_ATTR_ATTR] = _TAIL_CALL_LOAD_SUPER_ATTR_ATTR,
    [LOAD_SUPER_ATTR_METHOD] = _TAIL_CALL_LOAD_SUPER_ATTR_METHOD,
    [GET_ITER] = _TAIL_CALL_GET_ITER,
    [GET_YIELD_FROM_ITER] = _TAIL_CALL_GET_YIELD_FROM_ITER,
    [LOAD_ATTR_CLASS] = _TAIL_CALL_LOAD_ATTR_CLASS,
    [LOAD_BUILD_CLASS] = _TAIL_CALL_LOAD_BUILD_CLASS,
    [LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN] = _TAIL_CALL_LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN,
    [LOAD_ATTR_INSTANCE_VALUE] = _TAIL_CALL_LOAD_ATTR_INSTANCE_VALUE,
    [LOAD_ASSERTION_ERROR] = _TAIL_CALL_LOAD_ASSERTION_ERROR,
    [RETURN_GENERATOR] = _TAIL_CALL_RETURN_GENERATOR,
    [LOAD_ATTR_MODULE] = _TAIL_CALL_LOAD_ATTR_MODULE,
    [LOAD_ATTR_PROPERTY] = _TAIL_CALL_LOAD_ATTR_PROPERTY,
    [LOAD_ATTR_SLOT] = _TAIL_CALL_LOAD_ATTR_SLOT,
    [LOAD_ATTR_WITH_HINT] = _TAIL_CALL_LOAD_ATTR_WITH_HINT,
    [LOAD_ATTR_METHOD_LAZY_DICT] = _TAIL_CALL_LOAD_ATTR_METHOD_LAZY_DICT,
    [LOAD_ATTR_METHOD_NO_DICT] = _TAIL_CALL_LOAD_ATTR_METHOD_NO_DICT,
    [LOAD_ATTR_METHOD_WITH_VALUES] = _TAIL_CALL_LOAD_ATTR_METHOD_WITH_VALUES,
    [RETURN_VALUE] = _TAIL_CALL_RETURN_VALUE,
    [LOAD_CONST__LOAD_FAST] = _TAIL_CALL_LOAD_CONST__LOAD_FAST,
    [SETUP_ANNOTATIONS] = _TAIL_CALL_SETUP_ANNOTATIONS,
    [LOAD_FAST__LOAD_CONST] = _TAIL_CALL_LOAD_FAST__LOAD_CONST,
    [LOAD_LOCALS] = _TAIL_CALL_LOAD_LOCALS,
    [LOAD_FAST__LOAD_FAST] = _TAIL_CALL_LOAD_FAST__LOAD_FAST,
    [POP_EXCEPT] = _TAIL_CALL_POP_EXCEPT,
    [STORE_NAME] = _TAIL_CALL_STORE_NAME,
    [DELETE_NAME] = _TAIL_CALL_DELETE_NAME,
    [UNPACK_SEQUENCE] = _TAIL_CALL_UNPACK_SEQUENCE,
    [FOR_ITER] = _TAIL_CALL_FOR_ITER,
    [UNPACK_EX] = _TAIL_CALL_UNPACK_EX,
    [STORE_ATTR] = _TAIL_CALL_STORE_ATTR,
    [DELETE_ATTR] = _TAIL_CALL_DELETE_ATTR,
    [STORE_GLOBAL] = _TAIL_CALL_STORE_GLOBAL,
    [DELETE_GLOBAL] = _TAIL_CALL_DELETE_GLOBAL,
    [SWAP] = _TAIL_CALL_SWAP,
    [LOAD_CONST] = _TAIL_CALL_LOAD_CONST,
    [LOAD_NAME] = _TAIL_CALL_LOAD_NAME,
    [BUILD_TUPLE] = _TAIL_CALL_BUILD_TUPLE,
    [BUILD_LIST] = _TAIL_CALL_BUILD_LIST,
    [BUILD_SET] = _TAIL_CALL_BUILD_SET,
    [BUILD_MAP] = _TAIL_CALL_BUILD_MAP,
    [LOAD_ATTR] = _TAIL_CALL_LOAD_ATTR,
    [COMPARE_OP] = _TAIL_CALL_COMPARE_OP,
    [IMPORT_NAME] = _TAIL_CALL_IMPORT_NAME,
    [IMPORT_FROM] = _TAIL_CALL_IMPORT_FROM,
    [JUMP_FORWARD] = _TAIL_CALL_JUMP_FORWARD,
    [LOAD_GLOBAL_BUILTIN] = _TAIL_CALL_LOAD_GLOBAL_BUILTIN,
    [LOAD_GLOBAL_MODULE] = _TAIL_CALL_LOAD_GLOBAL_MODULE,
    [STORE_ATTR_INSTANCE_VALUE] = _TAIL_CALL_STORE_ATTR_INSTANCE_VALUE,
    [POP_JUMP_IF_FALSE] = _TAIL_CALL_POP_JUMP_IF_FALSE,
    [POP_JUMP_IF_TRUE] = _TAIL_CALL_POP_JUMP_IF_TRUE,
    [LOAD_GLOBAL] = _TAIL_CALL_LOAD_GLOBAL,
    [IS_OP] = _TAIL_CALL_IS_OP,
    [CONTAINS_OP] = _TAIL_CALL_CONTAINS_OP,
    [RERAISE] = _TAIL_CALL_RERAISE,
    [COPY] = _TAIL_CALL_COPY,
    [RETURN_CONST] = _TAIL_CALL_RETURN_CONST,
    [BINARY_OP] = _TAIL_CALL_BINARY_OP,
    [SEND] = _TAIL_CALL_SEND,
    [LOAD_FAST] = _TAIL_CALL_LOAD_FAST,
    [STORE_FAST] = _TAIL_CALL_STORE_FAST,
    [DELETE_FAST] = _TAIL_CALL_DELETE_FAST,
    [LOAD_FAST_CHECK] = _TAIL_CALL_LOAD_FAST_CHECK,
    [POP_JUMP_IF_NOT_NONE] = _TAIL_CALL_POP_JUMP_IF_NOT_NONE,
    [POP_JUMP_IF_NONE] = _TAIL_CALL_POP_JUMP_IF_NONE,
    [RAISE_VARARGS] = _TAIL_CALL_RAISE_VARARGS,
    [GET_AWAITABLE] = _TAIL_CALL_GET_AWAITABLE,
    [MAKE_FUNCTION] = _TAIL_CALL_MAKE_FUNCTION,
    [BUILD_SLICE] = _TAIL_CALL_BUILD_SLICE,
    [JUMP_BACKWARD_NO_INTERRUPT] = _TAIL_CALL_JUMP_BACKWARD_NO_INTERRUPT,
    [MAKE_CELL] = _TAIL_CALL_MAKE_CELL,
    [LOAD_CLOSURE] = _TAIL_CALL_LOAD_CLOSURE,
    [LOAD_DEREF] = _TAIL_CALL_LOAD_DEREF,
    [STORE_DEREF] = _TAIL_CALL_STORE_DEREF,
    [DELETE_DEREF] = _TAIL_CALL_DELETE_DEREF,
    [JUMP_BACKWARD] = _TAIL_CALL_JUMP_BACKWARD,
    [LOAD_SUPER_ATTR] = _TAIL_CALL_LOAD_SUPER_ATTR,
    [CALL_FUNCTION_EX] = _TAIL_CALL_CALL_FUNCTION_EX,
    [LOAD_FAST_AND_CLEAR] = _TAIL_CALL_LOAD_FAST_AND_CLEAR,
    [EXTENDED_ARG] = _TAIL_CALL_EXTENDED_ARG,
    [LIST_APPEND] = _TAIL_CALL_LIST_APPEND,
    [SET_ADD] = _TAIL_CALL_SET_ADD,
    [MAP_ADD] = _TAIL_CALL_MAP_ADD,
    [STORE_ATTR_SLOT] = _TAIL_CALL_STORE_ATTR_SLOT,
    [COPY_FREE_VARS] = _TAIL_CALL_COPY_FREE_VARS,
    [YIELD_VALUE] = _TAIL_CALL_YIELD_VALUE,
    [RESUME] = _TAIL_CALL_RESUME,
    [MATCH_CLASS] = _TAIL_CALL_MATCH_CLASS,
    [STORE_ATTR_WITH_HINT] = _TAIL_CALL_STORE_ATTR_WITH_HINT,
    [STORE_FAST__LOAD_FAST] = _TAIL_CALL_STORE_FAST__LOAD_FAST,
    [FORMAT_VALUE] = _TAIL_CALL_FORMAT_VALUE,
    [BUILD_CONST_KEY_MAP] = _TAIL_CALL_BUILD_CONST_KEY_MAP,
    [BUILD_STRING] = _TAIL_CALL_BUILD_STRING,
    [STORE_FAST__STORE_FAST] = _TAIL_CALL_STORE_FAST__STORE_FAST,
    [STORE_SUBSCR_DICT] = _TAIL_CALL_STORE_SUBSCR_DICT,
    [STORE_SUBSCR_LIST_INT] = _TAIL_CALL_STORE_SUBSCR_LIST_INT,
    [UNPACK_SEQUENCE_LIST] = _TAIL_CALL_UNPACK_SEQUENCE_LIST,
    [LIST_EXTEND] = _TAIL_CALL_LIST_EXTEND,
    [SET_UPDATE] = _TAIL_CALL_SET_UPDATE,
    [DICT_MERGE] = _TAIL_CALL_DICT_MERGE,
    [DICT_UPDATE] = _TAIL_CALL_DICT_UPDATE,
    [UNPACK_SEQUENCE_TUPLE] = _TAIL_CALL_UNPACK_SEQUENCE_TUPLE,
    [UNPACK_SEQUENCE_TWO_TUPLE] = _TAIL_CALL_UNPACK_SEQUENCE_TWO_TUPLE,
    [SEND_GEN] = _TAIL_CALL_SEND_GEN,
    [CALL] = _TAIL_CALL_CALL,
    [KW_NAMES] = _TAIL_CALL_KW_NAMES,
    [CALL_INTRINSIC_1] = _TAIL_CALL_CALL_INTRINSIC_1,
    [CALL_INTRINSIC_2] = _TAIL_CALL_CALL_INTRINSIC_2,
    [LOAD_FROM_DICT_OR_GLOBALS] = _TAIL_CALL_LOAD_FROM_DICT_OR_GLOBALS,
    [LOAD_FROM_DICT_OR_DEREF] = _TAIL_CALL_LOAD_FROM_DICT_OR_DEREF,
    [INSTRUMENTED_LOAD_SUPER_ATTR] = _TAIL_CALL_INSTRUMENTED_LOAD_SUPER_ATTR,
    [INSTRUMENTED_POP_JUMP_IF_NONE] = _TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_NONE,
    [INSTRUMENTED_POP_JUMP_IF_NOT_NONE] = _TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_NOT_NONE,
    [INSTRUMENTED_RESUME] = _TAIL_CALL_INSTRUMENTED_RESUME,
    [INSTRUMENTED_CALL] = _TAIL_CALL_INSTRUMENTED_CALL,
    [INSTRUMENTED_RETURN_VALUE] = _TAIL_CALL_INSTRUMENTED_RETURN_VALUE,
    [INSTRUMENTED_YIELD_VALUE] = _TAIL_CALL_INSTRUMENTED_YIELD_VALUE,
    [INSTRUMENTED_CALL_FUNCTION_EX] = _TAIL_CALL_INSTRUMENTED_CALL_FUNCTION_EX,
    [INSTRUMENTED_JUMP_FORWARD] = _TAIL_CALL_INSTRUMENTED_JUMP_FORWARD,
    [INSTRUMENTED_JUMP_BACKWARD] = _TAIL_CALL_INSTRUMENTED_JUMP_BACKWARD,
    [INSTRUMENTED_RETURN_CONST] = _TAIL_CALL_INSTRUMENTED_RETURN_CONST,
    [INSTRUMENTED_FOR_ITER] = _TAIL_CALL_INSTRUMENTED_FOR_ITER,
    [INSTRUMENTED_POP_JUMP_IF_FALSE] = _TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_FALSE,
    [INSTRUMENTED_POP_JUMP_IF_TRUE] = _TAIL_CALL_INSTRUMENTED_POP_JUMP_IF_TRUE,
    [INSTRUMENTED_END_FOR] = _TAIL_CALL_INSTRUMENTED_END_FOR,
    [INSTRUMENTED_END_SEND] = _TAIL_CALL_INSTRUMENTED_END_SEND,
    [INSTRUMENTED_INSTRUCTION] = _TAIL_CALL_INSTRUMENTED_INSTRUCTION,
    [INSTRUMENTED_LINE] = _TAIL_CALL_INSTRUMENTED_LINE,
    [169] = _TAIL_CALL_UNKNOWN_OPCODE,
    [170] = _TAIL_CALL_UNKNOWN_OPCODE,
    [177] = _TAIL_CALL_UNKNOWN_OPCODE,
    [178] = _TAIL_CALL_UNKNOWN_OPCODE,
    [179] = _TAIL_CALL_UNKNOWN_OPCODE,
    [180] = _TAIL_CALL_UNKNOWN_OPCODE,
    [181] = _TAIL_CALL_UNKNOWN_OPCODE,
    [182] = _TAIL_CALL_UNKNOWN_OPCODE,
    [183] = _TAIL_CALL_UNKNOWN_OPCODE,
    [184] = _TAIL_CALL_UNKNOWN_OPCODE,
    [185] = _TAIL_CALL_UNKNOWN_OPCODE,
    [186] = _TAIL_CALL_UNKNOWN_OPCODE,
    [187] = _TAIL_CALL_UNKNOWN_OPCODE,
    [188] = _TAIL_CALL_UNKNOWN_OPCODE,
    [189] = _TAIL_CALL_UNKNOWN_OPCODE,
    [190] = _TAIL_CALL_UNKNOWN_OPCODE,
    [191] = _TAIL_CALL_UNKNOWN_OPCODE,
    [192] = _TAIL_CALL_UNKNOWN_OPCODE,
    [193] = _TAIL_CALL_UNKNOWN_OPCODE,
    [194] = _TAIL_CALL_UNKNOWN_OPCODE,
    [195] = _TAIL_CALL_UNKNOWN_OPCODE,
    [196] = _TAIL_CALL_UNKNOWN_OPCODE,
    [197] = _TAIL_CALL_UNKNOWN_OPCODE,
    [198] = _TAIL_CALL_UNKNOWN_OPCODE,
    [199] = _TAIL_CALL_UNKNOWN_OPCODE,
    [200] = _TAIL_CALL_UNKNOWN_OPCODE,
    [201] = _TAIL_CALL_UNKNOWN_OPCODE,
    [202] = _TAIL_CALL_UNKNOWN_OPCODE,
    [203] = _TAIL_CALL_UNKNOWN_OPCODE,
    [204] = _TAIL_CALL_UNKNOWN_OPCODE,
    [205] = _TAIL_CALL_UNKNOWN_OPCODE,
    [206] = _TAIL_CALL_UNKNOWN_OPCODE,
    [207] = _TAIL_CALL_UNKNOWN_OPCODE,
    [208] = _TAIL_CALL_UNKNOWN_OPCODE,
    [209] = _TAIL_CALL_UNKNOWN_OPCODE,
    [210] = _TAIL_CALL_UNKNOWN_OPCODE,
    [211] = _TAIL_CALL_UNKNOWN_OPCODE,
    [212] = _TAIL_CALL_UNKNOWN_OPCODE,
    [213] = _TAIL_CALL_UNKNOWN_OPCODE,
    [214] = _TAIL_CALL_UNKNOWN_OPCODE,
    [215] = _TAIL_CALL_UNKNOWN_OPCODE,
    [216] = _TAIL_CALL_UNKNOWN_OPCODE,
    [217] = _TAIL_CALL_UNKNOWN_OPCODE,
    [218] = _TAIL_CALL_UNKNOWN_OPCODE,
    [219] = _TAIL_CALL_UNKNOWN_OPCODE,
    [220] = _TAIL_CALL_UNKNOWN_OPCODE,
    [221] = _TAIL_CALL_UNKNOWN_OPCODE,
    [222] = _TAIL_CALL_UNKNOWN_OPCODE,
    [223] = _TAIL_CALL_UNKNOWN_OPCODE,
    [224] = _TAIL_CALL_UNKNOWN_OPCODE,
    [225] = _TAIL_CALL_UNKNOWN_OPCODE,
    [226] = _TAIL_CALL_UNKNOWN_OPCODE,
    [227] = _TAIL_CALL_UNKNOWN_OPCODE,
    [228] = _TAIL_CALL_UNKNOWN_OPCODE,
    [229] = _TAIL_CALL_UNKNOWN_OPCODE,
    [230] = _TAIL_CALL_UNKNOWN_OPCODE,
    [231] = _TAIL_CALL_UNKNOWN_OPCODE,
    [232] = _TAIL_CALL_UNKNOWN_OPCODE,
    [233] = _TAIL_CALL_UNKNOWN_OPCODE,
    [234] = _TAIL_CALL_UNKNOWN_OPCODE,
    [235] = _TAIL_CALL_UNKNOWN_OPCODE,
    [236] = _TAIL_CALL_UNKNOWN_OPCODE,
    [255] = _TAIL_CALL_UNKNOWN_OPCODE,
};
#endif /* Py_TAIL_CALL_INTERP */
